// Code generated by "stringer -type=Gesture"; DO NOT EDIT.

package apds9960

import "fmt"

const _Gesture_name = "NoneLeftRightUpDownNearFarAll"

var _Gesture_index = [...]uint8{0, 4, 8, 13, 15, 19, 23, 26, 29}

func (i Gesture) String() string {
	if i < 0 || i >= Gesture(len(_Gesture_index)-1) {
		return fmt.Sprintf("Gesture(%d)", i)
	}
	return _Gesture_name[_Gesture_index[i]:_Gesture_index[i+1]]
}
